Repository yiisoft/yii-middleware, pull requests merged in 2023-05, with the labels that each got.

#57 Fix mutants, part 1
  README.md
  src/TrustedHostsNetworkResolver.php
  tests/TrustedHostsNetworkResolverTest.php
Labels: type:task, type:test

#59 Fix remaining mutants, part 2
  psalm.xml
  rector.php
  src/BasicNetworkResolver.php
  src/Exception/BadUriPrefixException.php
  src/HttpCache.php
  src/IpFilter.php
  tests/BasicNetworkResolverTest.php
  tests/Exception/BadUriPrefixExceptionTest.php
  tests/HttpCacheTest.php
Labels: type:test

#61 Fix docs and naming
  README.md
  src/AllowAllCors.php
  src/ForceSecureConnection.php
  src/HttpCache.php
  src/IpFilter.php
  src/Locale.php
  src/Redirect.php
  src/SubFolder.php
  src/TrustedHeaderProtocolResolver.php
  src/TrustedHostsNetworkResolver.php
  tests/LocaleTest.php
  tests/SubFolderTest.php
  tests/TrustedHeaderProtocolResolverTest.php
Labels: status:code review, type:docs

#63 Fix remaining mutants, part 3
  .github/workflows/bc.yml_
  .github/workflows/build.yml
  .github/workflows/composer-require-checker.yml
  .github/workflows/mutation.yml
  .github/workflows/rector.yml
  .github/workflows/static.yml
  composer.json
  src/HttpCache.php
  src/IpFilter.php
  src/Locale.php
  src/SubFolder.php
  tests/HttpCacheTest.php
  tests/IpFilterTest.php
  tests/LocaleTest.php
  tests/SubFolderTest.php
Labels: type:task, type:test

#65 Fix remaining mutants, part 4
  src/Locale.php
  src/TrustedHostsNetworkResolver.php
  tests/LocaleTest.php
  tests/TestAsset/MockRequestHandler.php
  tests/TrustedHostsNetworkResolverTest.php
Labels: type:test

#67 Fix remaining mutants, part 5
  src/TrustedHostsNetworkResolver.php
  tests/TrustedHostsNetworkResolverTest.php
Labels: type:bug, type:task, type:test

#70 `Locale` - Make saving locale to cookies optional
  .github/workflows/mutation.yml
  README.md
  src/Locale.php
  src/TrustedHeaderProtocolResolver.php
  src/TrustedHostsNetworkResolver.php
  tests/LocaleTest.php
  tests/TrustedHeaderProtocolResolverTest.php
  tests/TrustedHostsNetworkResolverTest.php
Labels: type:bug

#71 `Locale` - refactor, improve finding and saving locale, fix release blocking issues
  src/Locale.php
  tests/LocaleTest.php
  tests/TestAsset/MockRequestHandler.php
Labels: type:bug

#81 Fix Github Actions
  .github/workflows/build.yml
  .github/workflows/composer-require-checker.yml
  .github/workflows/mutation.yml
  .github/workflows/rector.yml
  .github/workflows/static.yml
  .scrutinizer.yml
Labels: type:bug

#91 Corrections for PR 88
  README.md
  composer.json
Labels: type:docs

#82 Make saving to session optional
  README.md
  src/Event/SetLocaleEvent.php
  src/Locale.php
  tests/LocaleTest.php
Labels: type:enhancement

#92 Rename `SubFolder` to `Subfolder`
  README.md
  src/Subfolder.php
  tests/SubfolderTest.php
Labels: type:task

#93 Remove `minimum-stability` from `composer.json`
  composer.json
Labels: type:task

#94 Actualize and enable BC workflow
  .github/workflows/bc.yml
Labels: type:task

#95 Remove unused network utilities dependency
  CHANGELOG.md
  composer.json
Labels: dependencies
